### PR TITLE
PHP 8 attributes support

### PR DESCRIPTION
**Pull request by mbolli**
So we want to ditch doctrine annotations completely. 

- added AttributeDriver and added tests for it (basically copied over from `AnnotationDriverTest` including the test classes)
- added ClassDriverTrait to reduce AttributeDriver/AnnotationDriver redundancies
- annotations are not working at all currently - they need a constructor with only one array parameter - attributes need a constructor with all typed parameters
- It might be possible to make annotations work with the `@NamedArgumentConstructor` annotation but for me the focus was on making attributes work

Needs a bit of cleaning for a release, and maybe it would be an idea to make a 3.x branch with no annotation support.

### CODE REVIEW

**Comment by mbolli** [comment]
@juliangut if you'd make a release of your latest commits with attribute support, I could close this PR.

**Comment by juliangut** [comment]
I'm sorry I haven't payed attention to this project

I'm now working on several packages including this and I'd like to ask you how do you feel about ditching php<8.1 in the next release

**Comment by mbolli** [comment]
@juliangut no worries! I'm all for `^8.1` :)

**Comment by juliangut** [comment]
@mbolli while I'm not completely done with the changes I want to introduce, still working on improving internal structures and caching performance, if you'd be so kind to try the code in master branch it'd help a lot. Mind the "migration from 2.x" section on readme file

I think it could be ready for release this week

**Comment by mbolli** [comment]
@juliangut Thanks! 

The only dealbreaker right now is that PhpDriver is final. I have classes extending it. 
The rest (narrower types, e.g. array for Route methods) need migration on my part, but I welcome the BC. 
IMHO deprecating the annotations is not necessary as it will be a major release. I'd remove them altogether.

**Comment by juliangut** [comment]
I've recovered the option to add single method as string, I think it simplifies most common scenario

Also, I'd like to ask you what is your use case to extend from PhpDriver, the final can of course be reverted but I'm curious

**Comment by mbolli** [comment]
I have two classes extending `PhpDriver`:

- `PageDriver` gets pages from the db and maps their alias to one of three invokables (display, redirect, fallback)
- `RedirectDriver` gets redirects from the db and maps their alias to the redirect invokable (301, 302, internal redirect)

**Comment by juliangut** [comment]
I see your use case is fair, and actually it probably should be considered in mapping library, but anyway given you're not actually using the loading from file part of PhpDriver wouldn't you be better using FileMappingTrait and implementing your own driver?

```php

declare(strict_types=1);

use Jgut\Mapping\Driver\DriverInterface;
use Jgut\Slim\Routing\Mapping\Driver\FileMappingTrait;

final class PageDriver implements DriverInterface
{
    use FileMappingTrait;

    protected function getMappingData(): array
    {
        // Collect from DDBB ,,,
        return [
            [
                'name' => 'displayOne',
                'methods' => 'GET',
                'pattern' => '/routeOne',
                'invokable' => 'DisplayClass:display',
            ],
        ];
    }
}
```

```php
declare(strict_types=1);

use Jgut\Mapping\Driver\DriverFactoryInterface;
use Jgut\Mapping\Driver\DriverInterface;
use Jgut\Mapping\Exception\DriverException;

final class DdBbDriverFactory implements DriverFactoryInterface
{
    public function getDriver(array $mappingSource): DriverInterface
    {
        $type = $mappingSource['type'] ?? null;
        return match($type) {
            'page' => $this->getPageDriver(),
            'redirect' => $this->getRedirectDriver(),
            default => throw new DriverException(sprintf('"%s" is not a valid metadata mapping driver.', $type)),
        };
    }

    private function getPageDriver(): DriverInterface
    {
        return new PageDriver();
    }

    private function getRedirectDriver(): DriverInterface
    {
        return new RedirectDriver();
    }
}
```

**Comment by mbolli** [comment]
That should work too! I will test it tomorrow, thanks.

**Comment by mbolli** [comment]
Using my own DriverFactory works perfectly. 

I saw that I used to extend from ViewResponse, TwigViewResponseHandler and JsonResponseHandler as well, but was able to get around it by extending the abstract base classes.

**Comment by juliangut** [comment]
Hi @mbolli

I think all changes and additions are done, for the moment I'll keep Annotations though I agree everyone on PHP8 should be using Attributes instead

Please test master branch to see if you find any trouble updating (see https://github.com/juliangut/slim-routing#migration-from-2x) and release will be probably ready by friday

**Comment by mbolli** [comment]
I already migrated and everything is working as it should!
I don't know how many users the library has, but maybe it should be mentioned in the migration chapter that most classes are now final. 
/edit ah, I now see you mentioned it already

**Comment by mbolli** [comment]
@juliangut do you think it's ready for a release?

**Comment by juliangut** [comment]
Great new @mbolli I've just published 3.0, thank your for testing it and for your patience

**Comment by mbolli** [comment]
Nice, thanks for your work! Thumbs up!

**Pull request closed without merging**
